replicaCount: 1

image:
  repository: haseeb497/15aug
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: false
  name: ""
  nginxClassName: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
